version: "3"
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    build:
      context: ./db
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
  go:
    image: go
    build:
      context: ./go
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"

  node:
    image: node
    build:
      context: ./node
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"