version: "3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
  go:
    image: go
    build:
      context: ./go
    depends_on:
      - db
    ports:
      - "8000:8000"

  node:
    image: node
    build:
      context: ./node
    depends_on:
      - db
    ports:
      - "3000:3000"